name: Cache images

on:
  workflow_dispatch:

jobs:
  cache-images:
    runs-on: ubuntu-latest
    steps:

    - name: download
      run: |
        curl --fail -L -o CentOS-Stream-9.iso https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/iso/CentOS-Stream-9-latest-x86_64-dvd1.iso
        curl --fail -L -o Alma-9.iso https://repo.almalinux.org/almalinux/9/isos/x86_64/AlmaLinux-9-latest-x86_64-dvd.iso
        curl --fail -L -o cirros.img http://download.cirros-cloud.net/0.6.3/cirros-0.6.3-x86_64-disk.img

    - name: Upload CentOS-Stream-9.iso to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: CentOS-Stream-9.iso
        target: github-ci/centos
        cleanup: yes
        # it should be always overwritten, but just in case...
        keep_files_count: 1

    - name: Upload Alma-9.iso to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: Alma-9.iso
        target: github-ci/centos

    - name: Upload cirros.img to resources.ovirt.org
      uses: ovirt/ovirt-resources-upload-action@main
      with:
        username: ${{ secrets.SSH_USERNAME_FOR_RESOURCES_OVIRT_ORG }}
        key: ${{ secrets.SSH_KEY_FOR_RESOURCES_OVIRT_ORG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS_FOR_RESOURCES_OVIRT_ORG }}
        source: cirros.img
        target: github-ci/centos
