name: Push Selenium images to quay

on:
  workflow_dispatch:
    inputs:
      selenium_version:
        required: true
        type: string
        default: "4.5.0"

env:
  IMAGE_REGISTRY: quay.io
jobs:
  selenium-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ standalone-chrome, standalone-firefox ]
        tag: [ '${{ inputs.selenium_version }}' ]
        include:
          - image: video
            tag: latest
    steps:
      - name: Pull selenium images
        run: podman pull docker.io/selenium/${{ matrix.image }}:${{ matrix.tag }}
      - name: Tag the image
        run: podman tag docker.io/selenium/${{ matrix.image }}:${{ matrix.tag }} ovirt/selenium-${{ matrix.image }}:latest
      - name: Push to Quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ovirt/selenium-${{ matrix.image }}
          tags: latest
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME  }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
