name: Push latest Selenium images to quay

on:
  workflow_dispatch:
  # Build every first day of the month at 00:00
  schedule:
    - cron:  '0 0 1 * *'
env:
  IMAGE_REGISTRY: quay.io
jobs:
  selenium-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [ node-chrome-debug, node-firefox-debug, hub, video ]
    steps:
      - name: Pull latest selenium images
        run: podman pull docker.io/selenium/${{ matrix.image }}:latest
      - name: Tag the image
        run: podman tag docker.io/selenium/${{ matrix.image }}:latest ovirt/${{ matrix.image }}:latest
      - name: Push to Quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ovirt/${{ matrix.image }}
          tags: latest
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME  }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
